# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninjas',
            old_name='dojo_id',
            new_name='dojos_id',
        ),
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
